ASN1_SOURCES = \
	asn1/ANY.h \
	asn1/AlertLevel.h \
	asn1/AlgorithmIdentifier.h \
	asn1/BIT_STRING.h \
	asn1/BOOLEAN.h \
	asn1/ContentInfo.h \
	asn1/ContentType.h \
	asn1/Extension.h \
	asn1/Extensions.h \
	asn1/GeneralizedTime.h \
	asn1/GeneratorType.h \
	asn1/INTEGER.h \
	asn1/NativeEnumerated.h \
	asn1/NativeInteger.h \
	asn1/Notification.h \
	asn1/Notifications.h \
	asn1/OBJECT_IDENTIFIER.h \
	asn1/OCTET_STRING.h \
	asn1/PublicationContentInfo.h \
	asn1/PublicationVersion.h \
	asn1/SeedDescriptor.h \
	asn1/SeedDescriptors.h \
	asn1/SeedReport.h \
	asn1/SeedReportContent.h \
	asn1/SeedReportVersion.h \
	asn1/SeedValues.h \
	asn1/Signature.h \
	asn1/Signatures.h \
	asn1/SubjectPublicKeyInfo.h \
	asn1/TBSPublicationData.h \
	asn1/TBSSeedReportContent.h \
	asn1/UTF8String.h \
	asn1/UpdateURL.h \
	asn1/UpdateURLs.h \
	asn1/asn_SEQUENCE_OF.h \
	asn1/asn_SET_OF.h \
	asn1/asn_application.h \
	asn1/asn_codecs.h \
	asn1/asn_codecs_prim.h \
	asn1/asn_internal.h \
	asn1/asn_system.h \
	asn1/ber_decoder.h \
	asn1/ber_tlv_length.h \
	asn1/ber_tlv_tag.h \
	asn1/constr_SEQUENCE.h \
	asn1/constr_SEQUENCE_OF.h \
	asn1/constr_SET_OF.h \
	asn1/constr_TYPE.h \
	asn1/constraints.h \
	asn1/der_encoder.h \
	asn1/per_decoder.h \
	asn1/per_encoder.h \
	asn1/per_opentype.h \
	asn1/per_support.h \
	asn1/xer_decoder.h \
	asn1/xer_encoder.h \
	asn1/xer_support.h \
	asn1/ANY.c \
	asn1/AlertLevel.c \
	asn1/AlgorithmIdentifier.c \
	asn1/BIT_STRING.c \
	asn1/BOOLEAN.c \
	asn1/ContentInfo.c \
	asn1/ContentType.c \
	asn1/Extension.c \
	asn1/Extensions.c \
	asn1/GeneralizedTime.c \
	asn1/GeneratorType.c \
	asn1/INTEGER.c \
	asn1/NativeEnumerated.c \
	asn1/NativeInteger.c \
	asn1/Notification.c \
	asn1/Notifications.c \
	asn1/OBJECT_IDENTIFIER.c \
	asn1/OCTET_STRING.c \
	asn1/PublicationContentInfo.c \
	asn1/PublicationVersion.c \
	asn1/SeedDescriptor.c \
	asn1/SeedDescriptors.c \
	asn1/SeedReport.c \
	asn1/SeedReportContent.c \
	asn1/SeedReportVersion.c \
	asn1/SeedValues.c \
	asn1/Signature.c \
	asn1/Signatures.c \
	asn1/SubjectPublicKeyInfo.c \
	asn1/TBSPublicationData.c \
	asn1/TBSSeedReportContent.c \
	asn1/UTF8String.c \
	asn1/UpdateURL.c \
	asn1/UpdateURLs.c \
	asn1/asn_SEQUENCE_OF.c \
	asn1/asn_SET_OF.c \
	asn1/asn_codecs_prim.c \
	asn1/ber_decoder.c \
	asn1/ber_tlv_length.c \
	asn1/ber_tlv_tag.c \
	asn1/constr_SEQUENCE.c \
	asn1/constr_SEQUENCE_OF.c \
	asn1/constr_SET_OF.c \
	asn1/constr_TYPE.c \
	asn1/constraints.c \
	asn1/der_encoder.c \
	asn1/per_decoder.c \
	asn1/per_encoder.c \
	asn1/per_opentype.c \
	asn1/per_support.c \
	asn1/xer_decoder.c \
	asn1/xer_encoder.c \
	asn1/xer_support.c
