SeedDescriptor ::= SEQUENCE {
    signatureAlgorithm          AlgorithmIdentifier,
    generatorType               GeneratorType,
    preseedValue                OCTET STRING,
    preseedVerificationKey      SubjectPublicKeyInfo }

