TBSPublicationData ::= SEQUENCE {
    version                     PublicationVersion,
    intendedAudience            PublicationAudience,
    publishedAt                 GeneralizedTime,
    nextUpdateNotBefore         GeneralizedTime,
    nextUpdateNotAfter          GeneralizedTime,
    excludesPublishedBefore     GeneralizedTime OPTIONAL,
    notifications               Notifications,
    updateURLs                  UpdateURLs,
    extensions              [0] Extensions OPTIONAL }

