TBSSeedReport ::= SEQUENCE {
    version                     SeedReportVersion,
    signatureAlgorithm          AlgorithmIdentifier,
    generatorType               GeneratorType,
    preseedValues               PreseedValues,
    preseedVerificationKey      SubjectPublicKeyInfo,
    publisherName               UTF8String,
    seedReportChallenge         UTF8String,
    extensions              [0] Extensions OPTIONAL }

